# Generated by Django 6.0 on 2025-12-31 14:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name/title of the exam', max_length=255)),
                ('duration', models.IntegerField(help_text='Time limit for completing the exam in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('course', models.CharField(help_text='Associated course or subject', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Exam description', null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Total marks for the exam', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_score', models.DecimalField(decimal_places=2, help_text='Minimum score required to pass', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_datetime', models.DateTimeField(blank=True, help_text='When the exam becomes available', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, help_text='When the exam closes', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Instructions for students', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current status of the exam', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_datetime'], name='api_exam_status_231e30_idx'), models.Index(fields=['course'], name='api_exam_course_860024_idx'), models.Index(fields=['-created_at'], name='api_exam_created_aec6d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The actual question content')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank')], help_text='Type of question', max_length=20)),
                ('expected_answer', models.JSONField(help_text='The correct answer or answer key (format depends on question type)')),
                ('marks', models.DecimalField(decimal_places=2, help_text='Point value for the question', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.IntegerField(blank=True, help_text='Question sequence number within the exam', null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Difficulty level of the question', max_length=20, null=True)),
                ('topic', models.CharField(blank=True, help_text='Topic or category', max_length=255, null=True)),
                ('grading_criteria', models.TextField(blank=True, help_text='Grading criteria for essay questions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(help_text='The exam this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.exam')),
            ],
            options={
                'ordering': ['exam', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When the student began the exam')),
                ('submit_time', models.DateTimeField(help_text='When the student submitted the exam')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Final score received', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('grading_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the grading process', max_length=20)),
                ('grading_feedback', models.JSONField(blank=True, help_text='Detailed feedback on answers', null=True)),
                ('time_taken', models.IntegerField(blank=True, help_text='Duration the student took to complete in seconds', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which submission was made', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('attempt_number', models.IntegerField(default=1, help_text='Attempt number if retakes are allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(help_text='The exam being submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.exam')),
                ('student', models.ForeignKey(help_text='The student who submitted this exam', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submit_time'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.JSONField(help_text="The student's answer (format depends on question type)")),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, help_text='Marks awarded for this answer', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True, help_text='Feedback for this specific answer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(help_text='The question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='api.question')),
                ('submission', models.ForeignKey(help_text='The submission this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.submission')),
            ],
            options={
                'ordering': ['submission', 'question__order', 'question__id'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='api_questio_exam_id_874d86_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='api_questio_questio_ac5f03_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'exam'], name='api_submiss_student_007df8_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', '-submit_time'], name='api_submiss_student_7a3068_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['grading_status'], name='api_submiss_grading_e1cc91_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['exam', 'grading_status'], name='api_submiss_exam_id_c5db80_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'attempt_number'), name='unique_student_exam_attempt'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['submission', 'question'], name='api_answer_submiss_04ec0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_submission_question'),
        ),
    ]
